# -*- coding: utf-8 -*-
"""Build one .londonplugin from every manifest in catalog/games/.

    python tools/build_plugins.py            # everything
    python tools/build_plugins.py pokemon_emerald

Each game gets its own small project that links the SHARED
plugin/GenericEmulatorPlugin.cs and embeds its own manifest. That is why
entryType is the same class name in every package: each assembly carries
exactly one game.json, so the class cannot read another game's manifest.

The manifest is embedded rather than shipped beside the assembly because the
launcher's pack_plugin.py deliberately whitelists only assembly + deps +
plugin.json -- a loose game.json would never make it into the package.
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

ROOT = Path(__file__).resolve().parent.parent
GAMES = ROOT / "catalog" / "games"
BUILD = ROOT / "build"
DIST = ROOT / "dist"
SHARED = ROOT / "plugin" / "GenericEmulatorPlugin.cs"
LAUNCHER = ROOT.parent / "Multiworld-Launcher" / "LauncherV2.csproj"
PACKER = ROOT.parent / "Multiworld-Launcher" / "Tools" / "pack_plugin.py"
SCRIPTS = ROOT.parent / "Multiworld-Launcher" / "Plugins" / "Scripts"

ENTRY = "LauncherV2.Plugins.Catalog.GenericEmulatorPlugin"
AUTHOR = "Solida Games"

# How the game talks to Archipelago. GenericEmulatorPlugin drives BizHawk with
# the generic Lua connector and NOTHING ELSE, so a world on another protocol
# must be REFUSED rather than built.
#
# This is not theoretical: every SNES world in Archipelago subclasses SNIClient,
# which speaks to SNI (a separate program) rather than to a Lua script inside
# BizHawk. A plugin built for one of those would install cleanly, launch
# BizHawk, and then never connect -- silent, and worse than not shipping.
PROTOCOLS = {
    "bizhawk": True,    # BizHawkClient + connector_bizhawk_generic.lua
    "sni": False,       # SNIClient -- London has no SNI bridge yet
    "unknown": False,   # not established; do not guess
}

# Whether the game's WORLD overrides patch steps in Python (APPatchExtension).
# The patch container does not say -- the manifest looks ordinary -- so this
# has to be established by READING the world's rom.py, once, at manifest time.
#
# Two classes exist. NEW step names (MLSS's enemy_randomize) make the
# launcher's patcher refuse loudly -- safe. REUSED generic names with changed
# behaviour (FRLG's rev0/rev1 dispatch) make generic code produce silently
# corrupt ROMs -- that class MUST be replicated in Core/Patching/ApPatch.cs
# before the manifest may say 'replicated'.
PATCH_EXTENSION = {
    "none":       True,   # world audited, no extension - generic steps correct
    "replicated": True,   # extension replicated in ApPatch.cs (cite the source)
    "refused":    True,   # extension adds NEW step names - refused loudly
    "unaudited":  True,   # world source not available locally - flagged below
}

# What a game needs from the player. Anything outside this set is a typo or a
# half-finished rename, and either way we must not guess -- see check().
REQUIRES = {
    "own_copy": True,    # the player supplies the game file
    "mod":      False,   # the player owns the game; the plugin installs a mod
    "free":     False,   # the game itself is free to fetch
    "unknown":  False,   # not classified yet
}

CSPROJ = """<Project Sdk="Microsoft.NET.Sdk">

  <!-- Generated by tools/build_plugins.py from catalog/games/{gid}.json. -->
  <!-- Edit the manifest, not this file.                                  -->

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>{asm}</AssemblyName>
    <RootNamespace>LauncherV2.Plugins.Catalog</RootNamespace>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Version>{ver}</Version>
    <Company>Solida Games</Company>
    <Product>{name} plugin for Multiworld Launcher</Product>
  </PropertyGroup>

  <ItemGroup>
    <!-- Private=false: the launcher already has these types loaded. A copy   -->
    <!-- here would make IGamePlugin in the plugin a DIFFERENT type from the  -->
    <!-- one in the host, and the cast would fail.                            -->
    <ProjectReference Include="{launcher}" Private="false" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="{shared}" Link="GenericEmulatorPlugin.cs" />
    <EmbeddedResource Include="game.json" />
  </ItemGroup>

</Project>
"""


def asm_name(gid):
    return "Catalog" + "".join(p.title() for p in gid.split("_"))


def check(m, gid):
    """A manifest has to be buildable. A guess is worse than a refusal."""
    problems = []
    for field in ("id", "display_name", "platform"):
        if not m.get(field):
            problems.append("missing %s" % field)
    if m.get("id") != gid:
        problems.append("id=%r does not match the filename %r" % (m.get("id"), gid))
    if not re.match(r"^[a-z0-9][a-z0-9_]{1,63}$", m.get("id") or ""):
        problems.append("id is not a legal shape (a-z, 0-9, _)")

    # A value we do not recognise must NOT fall through to a default. If
    # "own_copy" ever gets renamed and one caller is missed, the plugin would
    # quietly stop asking the player for their own file -- silent and wrong.
    req = m.get("requires")
    if req not in REQUIRES:
        problems.append("requires=%r is not one of %s"
                        % (req, "/".join(sorted(REQUIRES))))

    # Default to bizhawk only when the manifest predates this field; an
    # explicit value is never second-guessed.
    proto = (m.get("client") or {}).get("protocol", "bizhawk")
    if proto not in PROTOCOLS:
        problems.append("client.protocol=%r is not one of %s"
                        % (proto, "/".join(sorted(PROTOCOLS))))
    elif not PROTOCOLS[proto]:
        problems.append("client.protocol=%r - GenericEmulatorPlugin only "
                        "drives BizHawk, so this would install and then never "
                        "connect" % proto)

    # The game-side half. Without a module under Plugins/Scripts/games/ the
    # connector loads nothing and the game sends no checks -- which is exactly
    # how every plugin looked before this was noticed: installs, loads, casts,
    # passes PluginCheck, and then does nothing.
    if PROTOCOLS.get(proto):
        mod = m.get("lua_module") or m.get("id")
        if not (SCRIPTS / "games" / (mod + ".lua")).is_file():
            problems.append("no RAM map: Plugins/Scripts/games/%s.lua does not "
                            "exist, so this game would launch and send nothing"
                            % mod)

    # The patch-extension audit is a REQUIRED answer, not a default: a missing
    # field means nobody read the world's rom.py, and that is how FRLG's
    # rev0/rev1 dispatch nearly shipped as silent corruption.
    ext = m.get("patch_extension")
    if ext not in PATCH_EXTENSION:
        problems.append("patch_extension=%r is not one of %s - read the "
                        "world's rom.py for APPatchExtension and answer"
                        % (ext, "/".join(sorted(PATCH_EXTENSION))))
    elif ext == "unaudited":
        problems.append("NOTE: patch_extension unaudited - a Python step "
                        "override would corrupt silently; audit before "
                        "checks_verified can ever be claimed")
    elif ext == "refused":
        problems.append("NOTE: world patches via custom Python steps - the "
                        "launcher refuses them loudly and plays unpatched")

    rom = m.get("rom") or {}
    if rom and not rom.get("size") and not rom.get("md5"):
        # Not an error -- but it belongs in the report rather than hidden.
        problems.append("NOTE: neither size nor md5 - can only warn, not reject")
    return problems


def build_one(path, results):
    gid = path.stem
    m = json.loads(path.read_text(encoding="utf-8"))

    problems = check(m, gid)
    hard = [p for p in problems if not p.startswith("NOTE:")]
    if hard:
        results.append((gid, "REJECTED", "; ".join(hard)))
        return

    asm = asm_name(gid)
    ver = m.get("version", "1.0.0")
    proj = BUILD / gid
    proj.mkdir(parents=True, exist_ok=True)

    # Only the fields the plugin actually reads. The _source fields stay in the
    # catalogue -- they are documentation for US, not for the program.
    embedded = {k: m[k] for k in
                ("id", "display_name", "subtitle", "platform", "ap_world_name",
                 "description", "checks_verified", "lua_module")
                if k in m}
    if m.get("rom"):
        embedded["rom"] = {k: m["rom"].get(k)
                           for k in ("description", "size", "md5")
                           if m["rom"].get(k) is not None}
    (proj / "game.json").write_text(
        json.dumps(embedded, indent=2, ensure_ascii=False), encoding="utf-8")

    # The game name goes into XML. "Mario & Luigi" with a bare & is illegal
    # XML, and MSBuild dies BEFORE the compiler starts -- a failure that looks
    # nothing like a C# error. Everything from the manifest gets escaped.
    (proj / (asm + ".csproj")).write_text(CSPROJ.format(
        gid=gid, asm=asm, ver=ver, name=xml_escape(m["display_name"]),
        launcher=os.path.relpath(LAUNCHER, proj),
        shared=os.path.relpath(SHARED, proj)), encoding="utf-8")

    (proj / "plugin.json").write_text(json.dumps({
        "apiVersion": 2,
        "gameId": gid,
        "displayName": m["display_name"],
        "subtitle": m.get("subtitle", ""),
        "version": ver,
        "author": AUTHOR,
        "authorContact": "https://github.com/solida1987/london-plugin-catalog",
        "assembly": asm + ".dll",
        "entryType": ENTRY,
        "declares": {
            "installsFiles": True,
            "downloadsFrom": [],
            "runsExternalProcess": True,
            "connectsToAp": True,
            "requiresOriginalGame": REQUIRES[m["requires"]],
        },
        "rulesAcknowledged": True,
    }, indent=2, ensure_ascii=False), encoding="utf-8")

    r = subprocess.run(["dotnet", "build", str(proj), "-c", "Release", "--nologo",
                        "-v", "quiet"], capture_output=True, text=True)
    if r.returncode != 0:
        # The last lines are "Time Elapsed" and an advert for workloads. Find
        # the lines that actually say what went wrong.
        lines = ((r.stdout or "") + "\n" + (r.stderr or "")).splitlines()
        real = [l.strip() for l in lines
                if " error " in l or l.strip().startswith("error")]
        results.append((gid, "BUILD FAILED",
                        " / ".join(real[:2]) if real
                        else " / ".join(l.strip() for l in lines[-4:] if l.strip())))
        return

    r = subprocess.run([sys.executable, str(PACKER), str(proj), "-o", str(DIST)],
                       capture_output=True, text=True)
    if r.returncode != 0:
        results.append((gid, "PACK FAILED", (r.stdout or r.stderr).strip()[-200:]))
        return

    note = [p for p in problems if p.startswith("NOTE:")]
    results.append((gid, "OK", note[0] if note else ""))


def main(argv):
    if not SHARED.is_file():
        print("missing %s" % SHARED)
        return 1

    wanted = argv[1:]
    paths = sorted(GAMES.glob("*.json"))
    if wanted:
        paths = [p for p in paths if p.stem in wanted]
    if not paths:
        print("no manifests to build")
        return 1

    DIST.mkdir(exist_ok=True)
    results = []
    for p in paths:
        print("building %s ..." % p.stem)
        build_one(p, results)

    print()
    width = max(len(g) for g, _, _ in results)
    for gid, status, note in results:
        print("  %-*s  %-13s %s" % (width, gid, status, note))

    bad = [r for r in results if r[1] != "OK"]
    print("\n%d/%d built" % (len(results) - len(bad), len(results)))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
